export const MOCK_COURSES = [
  { id: 1,  title: "Complete Python Bootcamp",           description: "Go from zero to hero in Python. Learn variables, functions, OOP, file I/O, and build 5 real projects.",                                              category: "Programming",  level: "Beginner",     lessonCount: 42, enrolledCount: 3241, instructorName: "Dr. Sarah Chen",   emoji: "🐍",  coverColor: "linear-gradient(135deg,#3b82f6,#1d4ed8)", image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&h=340&fit=crop&q=80",  rating: 4.9, introVideo: "https://www.youtube.com/embed/rfscVS0vtbw" },
  { id: 2,  title: "UI/UX Design Masterclass",           description: "Learn Figma from scratch, design systems, user research, and ship beautiful products people love.",                                                   category: "Design",       level: "Intermediate", lessonCount: 38, enrolledCount: 2187, instructorName: "Marco Vitelli",    emoji: "🎨",  coverColor: "linear-gradient(135deg,#ec4899,#9333ea)", image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=340&fit=crop&q=80",  rating: 4.8, introVideo: "https://www.youtube.com/embed/c9Wg6Cb_YlU"  },
  { id: 3,  title: "Data Science with Pandas",           description: "Master data wrangling, visualization, and machine learning pipelines using Python's most powerful library.",                                        category: "Data Science", level: "Intermediate", lessonCount: 55, enrolledCount: 1890, instructorName: "Prof. Aiko Tanaka", emoji: "📊",  coverColor: "linear-gradient(135deg,#10b981,#059669)", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=340&fit=crop&q=80",  rating: 4.7, introVideo: "https://www.youtube.com/embed/vmEHCJofslg"  },
  { id: 4,  title: "React & Next.js Complete Guide",     description: "Build full-stack web apps with React hooks, context, server components, and deploy to production.",                                               category: "Programming",  level: "Advanced",     lessonCount: 61, enrolledCount: 4102, instructorName: "James O'Brien",    emoji: "⚛️", coverColor: "linear-gradient(135deg,#06b6d4,#0284c7)", image: "https://images.unsplash.com/photo-1593720219276-0b1eacd0aef4?w=600&h=340&fit=crop&q=80", rating: 5.0, introVideo: "https://www.youtube.com/embed/w7ejDZ8SWv8"  },
  { id: 5,  title: "Digital Marketing Fundamentals",     description: "SEO, social media strategy, paid ads, email funnels — everything you need to grow any business online.",                                          category: "Marketing",    level: "Beginner",     lessonCount: 29, enrolledCount: 1560, instructorName: "Priya Nair",       emoji: "📱",  coverColor: "linear-gradient(135deg,#f59e0b,#d97706)", image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=340&fit=crop&q=80",  rating: 4.6, introVideo: "https://www.youtube.com/embed/bixR-KIJKYM"  },
  { id: 6,  title: "Music Theory for Producers",         description: "Understand scales, chords, rhythm, and harmony so you can write and produce music that moves people.",                                            category: "Music",        level: "Beginner",     lessonCount: 33, enrolledCount: 987,  instructorName: "Leon Baptiste",    emoji: "🎵",  coverColor: "linear-gradient(135deg,#8b5cf6,#7c3aed)", image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=340&fit=crop&q=80",  rating: 4.8, introVideo: "https://www.youtube.com/embed/rgaTLrZGlk0"  },
  { id: 7,  title: "JavaScript: The Complete Guide",     description: "Master modern JavaScript — ES6+, async/await, DOM manipulation, and build interactive web apps from scratch.",                                   category: "Programming",  level: "Beginner",     lessonCount: 58, enrolledCount: 5320, instructorName: "Alex Rivera",      emoji: "🟨",  coverColor: "linear-gradient(135deg,#f59e0b,#d97706)", image: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&h=340&fit=crop&q=80",  rating: 4.9, introVideo: "https://www.youtube.com/embed/PkZNo7MFNFg"  },
  { id: 8,  title: "Brand Identity Design",              description: "Create stunning logos, brand guidelines, and visual identities. Master typography, color theory, and Adobe Illustrator.",                        category: "Design",       level: "Beginner",     lessonCount: 31, enrolledCount: 1420, instructorName: "Sofia Mendes",     emoji: "✏️",  coverColor: "linear-gradient(135deg,#f43f5e,#e11d48)", image: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&h=340&fit=crop&q=80",  rating: 4.7, introVideo: "https://www.youtube.com/embed/l-S2Y3SF3jM"  },
  { id: 9,  title: "Machine Learning A-Z",               description: "From linear regression to neural networks. Build and deploy real ML models using scikit-learn and TensorFlow.",                                  category: "Data Science", level: "Advanced",     lessonCount: 74, enrolledCount: 2980, instructorName: "Prof. Aiko Tanaka", emoji: "🤖",  coverColor: "linear-gradient(135deg,#0ea5e9,#0284c7)", image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=340&fit=crop&q=80",  rating: 4.8, introVideo: "https://www.youtube.com/embed/GwIo3gDZCVQ"  },
  { id: 10, title: "Startup Business Fundamentals",      description: "Validate your idea, build an MVP, find product-market fit, and pitch to investors with confidence.",                                             category: "Business",     level: "Beginner",     lessonCount: 27, enrolledCount: 1875, instructorName: "David Park",        emoji: "🚀",  coverColor: "linear-gradient(135deg,#6366f1,#4f46e5)", image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=340&fit=crop&q=80",  rating: 4.6, introVideo: "https://www.youtube.com/embed/ZoqgAy3h4OM"  },
  { id: 11, title: "Content Marketing & SEO",            description: "Drive organic traffic with strategic content. Learn keyword research, on-page SEO, blogging, and link building.",                               category: "Marketing",    level: "Intermediate", lessonCount: 34, enrolledCount: 2100, instructorName: "Priya Nair",       emoji: "✍️",  coverColor: "linear-gradient(135deg,#10b981,#059669)", image: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=340&fit=crop&q=80",  rating: 4.7, introVideo: "https://www.youtube.com/embed/xsVTqzratPs"  },
  { id: 12, title: "Guitar for Beginners",               description: "Learn to play your first chords, strumming patterns, and songs within weeks. Acoustic and electric covered.",                                   category: "Music",        level: "Beginner",     lessonCount: 28, enrolledCount: 1340, instructorName: "Leon Baptiste",    emoji: "🎸",  coverColor: "linear-gradient(135deg,#f97316,#ea580c)", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=340&fit=crop&q=80",  rating: 4.9, introVideo: "https://www.youtube.com/embed/BBz-Jyr23M4"  },
  { id: 13, title: "Node.js & Express API Development",  description: "Build scalable REST APIs with Node.js, Express, MongoDB, authentication, and deploy to AWS.",                                                   category: "Programming",  level: "Intermediate", lessonCount: 47, enrolledCount: 2650, instructorName: "James O'Brien",    emoji: "🟢",  coverColor: "linear-gradient(135deg,#22c55e,#16a34a)", image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&h=340&fit=crop&q=80",  rating: 4.8, introVideo: "https://www.youtube.com/embed/Oe421EPjeBE"  },
  { id: 14, title: "Motion Design with After Effects",   description: "Create jaw-dropping animations, kinetic typography, and motion graphics for film, social, and apps.",                                          category: "Design",       level: "Intermediate", lessonCount: 44, enrolledCount: 980,  instructorName: "Sofia Mendes",     emoji: "🎬",  coverColor: "linear-gradient(135deg,#a855f7,#7c3aed)", image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&h=340&fit=crop&q=80",  rating: 4.6, introVideo: "https://www.youtube.com/embed/OB4-3VkFCJo"  },
  { id: 15, title: "Financial Modeling & Valuation",     description: "Build Excel models used by Wall Street analysts. DCF, LBO, M&A, and comparable company analysis.",                                             category: "Business",     level: "Advanced",     lessonCount: 52, enrolledCount: 1460, instructorName: "David Park",        emoji: "💹",  coverColor: "linear-gradient(135deg,#14b8a6,#0d9488)", image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=340&fit=crop&q=80",  rating: 4.9, introVideo: "https://www.youtube.com/embed/EJHPltmAULA"  },
  { id: 16, title: "SQL & Database Design",              description: "Write complex queries, design normalized schemas, and work with PostgreSQL, MySQL, and cloud databases.",                                        category: "Data Science", level: "Beginner",     lessonCount: 36, enrolledCount: 3100, instructorName: "Dr. Sarah Chen",   emoji: "🗄️", coverColor: "linear-gradient(135deg,#f59e0b,#b45309)", image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&h=340&fit=crop&q=80",  rating: 4.7, introVideo: "https://www.youtube.com/embed/HXV3zeQKqGY"  },
];

export const CATEGORIES = ["All", "Programming", "Design", "Business", "Marketing", "Data Science", "Music"];

export const STATS = [
  { num: "48K+", label: "Active Students",   icon: "👩‍🎓" },
  { num: "1.2K+", label: "Expert Instructors", icon: "🏫" },
  { num: "12K+", label: "Courses Available",  icon: "📚" },
  { num: "94%",  label: "Completion Rate",    icon: "🏆" },
];

export const TESTIMONIALS = [
  { name: "Aisha Patel",  role: "Frontend Dev @ Stripe",    text: "LearnPath completely changed my career. I went from marketing to frontend in 8 months using courses here.", avatar: "A", color: "#6C63FF" },
  { name: "Tom Eriksson", role: "Data Analyst @ Spotify",   text: "The Data Science courses are genuinely world-class. Better than anything I found on other platforms.",      avatar: "T", color: "#10b981" },
  { name: "Nina Okonkwo", role: "UX Lead @ Figma",          text: "Marco's Design Masterclass is the reason I got my job. The projects in the course built my whole portfolio.", avatar: "N", color: "#ec4899" },
];

// ─── REVIEWS ─────────────────────────────────────────────────────────────────
export const COURSE_REVIEWS = {
  1: [
    { id: 1, name: "Rahul Sharma", avatar: "R", color: "#6C63FF", rating: 5, date: "Feb 2026", comment: "Absolutely the best Python course I've taken. Dr. Sarah explains everything so clearly. I built my first web scraper after lesson 10!" },
    { id: 2, name: "Meena Gupta",  avatar: "M", color: "#10b981", rating: 5, date: "Jan 2026", comment: "Started from zero, now I'm writing scripts to automate my work. The projects are really practical and fun." },
    { id: 3, name: "James Wilson", avatar: "J", color: "#f59e0b", rating: 4, date: "Dec 2025", comment: "Great course overall. The OOP section was a bit fast but rewatching helped. Highly recommend for beginners." },
    { id: 4, name: "Priya Singh",  avatar: "P", color: "#ec4899", rating: 5, date: "Nov 2025", comment: "I got a job as a junior Python developer after completing this course. Worth every minute!" },
  ],
  2: [
    { id: 1, name: "Sofia L",   avatar: "S", color: "#a855f7", rating: 5, date: "Feb 2026", comment: "Marco is an amazing teacher. I went from knowing nothing about Figma to landing a freelance project in 3 months." },
    { id: 2, name: "Daniel K",  avatar: "D", color: "#06b6d4", rating: 4, date: "Jan 2026", comment: "The design systems section alone is worth it. My portfolio looks 10x better now." },
    { id: 3, name: "Aiko T",    avatar: "A", color: "#f43f5e", rating: 5, date: "Dec 2025", comment: "Best UX course online. Real world projects and very up to date with current design trends." },
  ],
  4: [
    { id: 1, name: "Alex M",  avatar: "A", color: "#06b6d4", rating: 5, date: "Feb 2026", comment: "This course is gold. The Next.js 14 App Router section is the most comprehensive I've seen anywhere online." },
    { id: 2, name: "Riya P",  avatar: "R", color: "#6C63FF", rating: 5, date: "Jan 2026", comment: "James explains complex concepts in a very simple way. I deployed my first full stack app after this course!" },
    { id: 3, name: "Kevin B", avatar: "K", color: "#10b981", rating: 4, date: "Dec 2025", comment: "Very detailed and practical. Some sections assume prior React knowledge so make sure you have basics first." },
  ],
  7: [
    { id: 1, name: "Tanvi R",     avatar: "T", color: "#f59e0b", rating: 5, date: "Feb 2026", comment: "Started this with zero coding knowledge. Now I can build interactive web pages. Alex is a brilliant teacher!" },
    { id: 2, name: "Mohammed A",  avatar: "M", color: "#6C63FF", rating: 5, date: "Jan 2026", comment: "The DOM manipulation section was exactly what I needed for my job. Super practical examples." },
    { id: 3, name: "Lisa C",      avatar: "L", color: "#ec4899", rating: 4, date: "Nov 2025", comment: "Thorough and well structured. A few topics could use more exercises but overall an excellent course." },
  ],
  9: [
    { id: 1, name: "Arjun D",  avatar: "A", color: "#0ea5e9", rating: 5, date: "Feb 2026", comment: "The neural networks section is fantastic. Very hands-on with real TensorFlow code. Best ML course I found." },
    { id: 2, name: "Fatima Z", avatar: "F", color: "#10b981", rating: 5, date: "Jan 2026", comment: "I passed my ML interview after doing this course. The deployment section especially helped me stand out." },
    { id: 3, name: "Chris N",  avatar: "C", color: "#a855f7", rating: 4, date: "Dec 2025", comment: "Excellent content. The math behind algorithms is explained intuitively without being too academic." },
  ],
};

// ─── QUIZZES ─────────────────────────────────────────────────────────────────
export const LESSON_QUIZZES = {
  101: { question: "Which command prints output in Python?",                        options: ["echo()", "console.log()", "print()", "output()"],                                              answer: 2 },
  102: { question: "Which is NOT a Python data type?",                              options: ["int", "float", "char", "bool"],                                                               answer: 2 },
  103: { question: "What keyword is used for conditional statements in Python?",    options: ["when", "if", "check", "case"],                                                                answer: 1 },
  104: { question: "Which loop is best when you know the number of iterations?",    options: ["while loop", "do-while loop", "for loop", "repeat loop"],                                    answer: 2 },
  105: { question: "What keyword defines a function in Python?",                    options: ["func", "function", "define", "def"],                                                          answer: 3 },
  201: { question: "What does UX stand for?",                                       options: ["User Experience", "User Extension", "Unified Experience", "User Execution"],                 answer: 0 },
  202: { question: "Figma is primarily used for?",                                  options: ["Video editing", "UI/UX Design", "3D modeling", "Code editing"],                              answer: 1 },
  401: { question: "Which hook manages state in a React functional component?",     options: ["useEffect", "useContext", "useState", "useRef"],                                              answer: 2 },
  402: { question: "What is the purpose of useEffect's dependency array?",          options: ["To declare variables", "To control when effect runs", "To import modules", "To define routes"], answer: 1 },
  701: { question: "JavaScript runs primarily in which environment?",               options: ["The server only", "The database", "The browser", "The compiler"],                            answer: 2 },
  702: { question: "Which keyword declares a variable that cannot be reassigned?",  options: ["let", "var", "const", "static"],                                                              answer: 2 },
  901: { question: "Machine learning is a subset of?",                              options: ["Robotics", "Artificial Intelligence", "Cloud Computing", "Web Development"],                 answer: 1 },
  902: { question: "Logistic regression is used for?",                              options: ["Predicting continuous values", "Image generation", "Classification problems", "Clustering"], answer: 2 },
};

export const DEFAULT_QUIZZES = [
  { question: "What is the main purpose of this lesson?",              options: ["To confuse students", "To introduce a core concept", "To test existing knowledge only", "To skip theory"],      answer: 1 },
  { question: "Which approach is best when learning something new?",   options: ["Memorize everything", "Skip practice", "Practice with real examples", "Read once and move on"],               answer: 2 },
  { question: "What should you do after completing a lesson?",         options: ["Nothing", "Try the examples yourself", "Skip to the final lesson", "Watch a movie"],                          answer: 1 },
];

// ─── HELPER: generate lessons for remaining courses ───────────────────────────
const makeLessons = (courseId, titles, videoUrls) =>
  titles.map((title, i) => ({
    id: courseId * 100 + i + 1,
    title,
    content: `This lesson covers: ${title}.\n\nKey points:\n• Understand the core concept\n• Follow the video above step by step\n• Practice the examples shown\n• Avoid common beginner mistakes\n• Apply what you learn in a small project`,
    orderNumber: i + 1,
    duration: `${12 + i * 3} min`,
    videoUrl: videoUrls[i] || videoUrls[0],
  }));

// ─── SEED LESSONS ─────────────────────────────────────────────────────────────
export const SEED_LESSONS = {
  1: [
    { id: 101, orderNumber: 1, duration: "12 min", videoUrl: "https://www.youtube.com/embed/rfscVS0vtbw", title: "Introduction & Environment Setup",   content: "Install Python 3.12 and VS Code. Run your first script.\n\nTopics:\n• Python REPL\n• Writing .py files\n• print() statements\n• Variable assignment\n• Indentation rules" },
    { id: 102, orderNumber: 2, duration: "18 min", videoUrl: "https://www.youtube.com/embed/khKv-8q7YmY", title: "Variables, Data Types & Operators",   content: "Python types: int, float, str, bool, None.\n\nOperators: +, -, *, /, //, %, **\nComparison: ==, !=, <, >, <=, >=\nLogical: and, or, not\n\nF-strings:\nname = 'Alice'\nprint(f'Hello {name}')  # Hello Alice" },
    { id: 103, orderNumber: 3, duration: "15 min", videoUrl: "https://www.youtube.com/embed/f4KOjWS_KZs", title: "Control Flow: if / elif / else",       content: "if condition:\n    do something\nelif another:\n    do something else\nelse:\n    fallback\n\nTernary:\nresult = 'pass' if score >= 50 else 'fail'" },
    { id: 104, orderNumber: 4, duration: "20 min", videoUrl: "https://www.youtube.com/embed/94UHCEmprCY", title: "Loops: for & while",                   content: "for i in range(5):\n    print(i)\n\nwhile count < 5:\n    count += 1\n\nbreak — exits loop\ncontinue — skips to next iteration" },
    { id: 105, orderNumber: 5, duration: "22 min", videoUrl: "https://www.youtube.com/embed/9Os0o3wzS_I", title: "Functions & Scope",                    content: "def greet(name, greeting='Hello'):\n    return f'{greeting}, {name}!'\n\nLambda:\nsquare = lambda x: x ** 2\n\nScope: Local -> Enclosing -> Global -> Built-in" },
    { id: 106, orderNumber: 6, duration: "24 min", videoUrl: "https://www.youtube.com/embed/W8KRzm-HUcc", title: "Lists, Tuples & Dictionaries",         content: "fruits = ['apple', 'banana']\nfruits.append('mango')\n\nList comprehension:\nsquares = [x**2 for x in range(10)]\n\nDict:\nperson = {'name': 'Alice', 'age': 25}\nfor k, v in person.items(): print(k, v)" },
    { id: 107, orderNumber: 7, duration: "28 min", videoUrl: "https://www.youtube.com/embed/JeznW_7DlB0", title: "Object-Oriented Programming",          content: "class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return f'{self.name} speaks'\n\ndog = Animal('Dog')\nprint(dog.speak())" },
    { id: 108, orderNumber: 8, duration: "20 min", videoUrl: "https://www.youtube.com/embed/NIWwJbo-9_8", title: "File Handling & Error Handling",       content: "with open('data.txt', 'r') as f:\n    content = f.read()\n\ntry:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print('Cannot divide by zero')\nfinally:\n    print('Always runs')" },
  ],
  2: [
    { id: 201, orderNumber: 1, duration: "14 min", videoUrl: "https://www.youtube.com/embed/c9Wg6Cb_YlU", title: "Introduction to UI/UX Design",         content: "UI = how it looks. UX = how it feels.\n\nDesign tools: Figma, Adobe XD, Sketch\n\nDesign process:\n1. Research\n2. Define\n3. Ideate\n4. Prototype\n5. Test\n6. Launch" },
    { id: 202, orderNumber: 2, duration: "20 min", videoUrl: "https://www.youtube.com/embed/FTFaQWZBqQ8", title: "Getting Started with Figma",           content: "Tools:\n• Frame (F): containers\n• Rectangle (R), Circle (O)\n• Text (T)\n\nCmds:\n• Ctrl+G: group\n• Ctrl+Alt+K: create component" },
    { id: 203, orderNumber: 3, duration: "18 min", videoUrl: "https://www.youtube.com/embed/AvgCkHrcj8w", title: "Typography & Color Theory",             content: "Fonts: Serif (formal), Sans-serif (modern), Display\n\nHierarchy: H1 48px > H2 32px > Body 16px\n\nColors: Complementary, Analogous, Triadic\nPalette: 1 primary + 1 accent + neutrals" },
    { id: 204, orderNumber: 4, duration: "25 min", videoUrl: "https://www.youtube.com/embed/lTIeZ2ahEkQ", title: "Wireframing & Prototyping",             content: "Wireframes are layout blueprints.\n\nPrototyping in Figma:\n1. Select frame\n2. Click Prototype tab\n3. Drag to next frame\n4. Set interaction\n5. Press Play to test" },
    { id: 205, orderNumber: 5, duration: "22 min", videoUrl: "https://www.youtube.com/embed/Hx02SaL_IH0", title: "Design Systems",                       content: "Design system = single source of truth.\n\nIncludes:\n• Color styles\n• Typography\n• Spacing (4,8,12,16,24,32px)\n• Components: buttons, inputs, cards\n• Icons & grid" },
    { id: 206, orderNumber: 6, duration: "20 min", videoUrl: "https://www.youtube.com/embed/wnxSALdpwuE", title: "User Research & Personas",              content: "Methods:\n• User interviews (5-8 people)\n• Surveys\n• Usability testing\n• Analytics\n\nPersona: Name, age, goals, pain points, tech level" },
  ],
  4: [
    { id: 401, orderNumber: 1, duration: "16 min", videoUrl: "https://www.youtube.com/embed/w7ejDZ8SWv8", title: "React Fundamentals Review",             content: "JSX: const el = <h1>Hello</h1>\nProps: read-only from parent\nState: data that changes\n\nfunc Counter() {\n  const [n, setN] = useState(0);\n  return <div>{n}</div>;\n}" },
    { id: 402, orderNumber: 2, duration: "24 min", videoUrl: "https://www.youtube.com/embed/O6P86uwfdR0", title: "useState & useEffect Deep Dive",        content: "const [count, setCount] = useState(0);\n\nuseEffect(() => {\n  fetchUser(userId);\n}, [userId]);\n\nCleanup:\nreturn () => clearInterval(timer);" },
    { id: 403, orderNumber: 3, duration: "28 min", videoUrl: "https://www.youtube.com/embed/5LrDIWkK_Bc", title: "Context API & useReducer",              content: "const Ctx = createContext();\n\n<Ctx.Provider value={{user}}>\n  <App />\n</Ctx.Provider>\n\nconst {user} = useContext(Ctx);\n\nuseReducer:\ndispatch({ type: 'ADD', payload: item });" },
    { id: 404, orderNumber: 4, duration: "32 min", videoUrl: "https://www.youtube.com/embed/wm5gMKuwSYk", title: "Next.js 14 App Router",                 content: "app/page.tsx → /\napp/about/page.tsx → /about\napp/blog/[id]/page.tsx → /blog/123\n\nServer Components: default, fast\nClient Components: add 'use client'\nLoading: loading.tsx" },
    { id: 405, orderNumber: 5, duration: "35 min", videoUrl: "https://www.youtube.com/embed/2OTq15A5s0Y", title: "Building & Deploying to Vercel",        content: "1. Push to GitHub\n2. vercel.com → Import repo\n3. Add env variables\n4. Deploy!\n\nFree: custom domain + auto deploys on every push" },
    { id: 406, orderNumber: 6, duration: "26 min", videoUrl: "https://www.youtube.com/embed/SqVLqvsiAYQ", title: "Performance Optimization",              content: "React.memo, useMemo, useCallback\nnext/image, next/font\n\nCore Web Vitals:\n• LCP < 2.5s\n• FID < 100ms\n• CLS < 0.1" },
  ],
  7: [
    { id: 701, orderNumber: 1, duration: "10 min", videoUrl: "https://www.youtube.com/embed/PkZNo7MFNFg", title: "Introduction to JavaScript",            content: "JavaScript makes web pages interactive.\n\nconsole.log('Hello World!');\nalert('Welcome!');\n\nRun in browser (F12 > Console) or Node.js" },
    { id: 702, orderNumber: 2, duration: "15 min", videoUrl: "https://www.youtube.com/embed/edlFjlzxkSI", title: "Variables & Data Types",                content: "var (old), let (reassignable), const (fixed)\n\nTypes: String, Number, Boolean, null, undefined, Object, Array\n\ntypeof 'hello' // 'string'\ntypeof 42      // 'number'" },
    { id: 703, orderNumber: 3, duration: "18 min", videoUrl: "https://www.youtube.com/embed/h33Srr5J9nY", title: "Functions & Arrow Functions",           content: "function greet(name) { return 'Hi ' + name; }\n\nArrow:\nconst greet = name => 'Hi ' + name;\n\nDefault param:\nconst greet = (name='World') => `Hi ${name}`;" },
    { id: 704, orderNumber: 4, duration: "20 min", videoUrl: "https://www.youtube.com/embed/oigfaZ5ApsM", title: "Arrays & Objects",                      content: "const nums = [1,2,3];\nnums.map(n => n*2)\nnums.filter(n => n>1)\nnums.reduce((a,b) => a+b, 0)\n\nconst p = {name:'Alice'};\nconst {name} = p; // destructuring\nconst p2 = {...p, age:25}; // spread" },
    { id: 705, orderNumber: 5, duration: "22 min", videoUrl: "https://www.youtube.com/embed/y17RuWkWdn8", title: "DOM Manipulation",                      content: "document.querySelector('.btn')\nel.innerHTML = 'New text';\nel.style.color = 'red';\nel.classList.add('active');\n\nbtn.addEventListener('click', () => {\n  alert('Clicked!');\n});" },
    { id: 706, orderNumber: 6, duration: "25 min", videoUrl: "https://www.youtube.com/embed/PoRJizFvM7s", title: "Async JavaScript & Fetch API",          content: "async function getData() {\n  try {\n    const res = await fetch(url);\n    const data = await res.json();\n    console.log(data);\n  } catch(e) {\n    console.error(e);\n  }\n}" },
  ],
  9: [
    { id: 901, orderNumber: 1, duration: "18 min", videoUrl: "https://www.youtube.com/embed/GwIo3gDZCVQ", title: "Introduction to Machine Learning",      content: "ML: computers learn from data.\n\nTypes:\n1. Supervised — labeled data\n2. Unsupervised — find patterns\n3. Reinforcement — rewards\n\nWorkflow: Collect > Clean > Train > Evaluate > Deploy" },
    { id: 902, orderNumber: 2, duration: "25 min", videoUrl: "https://www.youtube.com/embed/VmbA0pi2cRQ", title: "Linear & Logistic Regression",          content: "Linear: predict numbers\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\n\nLogistic: predict categories\nmodel = LogisticRegression()\nacc = model.score(X_test, y_test)" },
    { id: 903, orderNumber: 3, duration: "28 min", videoUrl: "https://www.youtube.com/embed/J4Wdy0Wc_xQ", title: "Decision Trees & Random Forests",      content: "Decision Tree:\ntree = DecisionTreeClassifier(max_depth=5)\ntree.fit(X_train, y_train)\n\nRandom Forest (100s of trees):\nrf = RandomForestClassifier(n_estimators=100)\nrf.feature_importances_" },
    { id: 904, orderNumber: 4, duration: "35 min", videoUrl: "https://www.youtube.com/embed/aircAruvnKk", title: "Neural Networks & Deep Learning",       content: "model = tf.keras.Sequential([\n  Dense(128, activation='relu'),\n  Dropout(0.2),\n  Dense(64, activation='relu'),\n  Dense(10, activation='softmax')\n])\nmodel.compile(optimizer='adam')\nmodel.fit(X_train, y_train, epochs=10)" },
    { id: 905, orderNumber: 5, duration: "30 min", videoUrl: "https://www.youtube.com/embed/s_ht4AKnWZg", title: "Model Deployment with Flask",           content: "import joblib\njoblib.dump(model, 'model.pkl')\n\n@app.route('/predict', methods=['POST'])\ndef predict():\n    data = request.json['features']\n    return jsonify({'result': int(model.predict([data])[0])})" },
    { id: 906, orderNumber: 6, duration: "32 min", videoUrl: "https://www.youtube.com/embed/X2vAabgKiuM", title: "Natural Language Processing",           content: "NLP: computers understand text.\n\nSteps:\n1. Tokenize\n2. Lowercase\n3. Remove stopwords\n4. Stem/Lemmatize\n5. Vectorize (TF-IDF)\n\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nX = TfidfVectorizer().fit_transform(docs)" },
  ],
  3:  makeLessons(3,  ["Intro to Data Science","Pandas Basics","Data Cleaning","Visualization with Matplotlib","Intro to Machine Learning","Feature Engineering"],  Array(6).fill("https://www.youtube.com/embed/vmEHCJofslg")),
  5:  makeLessons(5,  ["Intro to Digital Marketing","SEO Fundamentals","Social Media Marketing","Email Marketing","Google & Meta Ads","Analytics & Reporting"],      Array(6).fill("https://www.youtube.com/embed/bixR-KIJKYM")),
  6:  makeLessons(6,  ["Intro to Music Theory","Scales & Keys","Chords & Harmony","Rhythm & Time Signatures","Theory in Production","Melody Writing"],               Array(6).fill("https://www.youtube.com/embed/rgaTLrZGlk0")),
  8:  makeLessons(8,  ["Intro to Brand Identity","Logo Design Principles","Typography for Branding","Color Psychology","Brand Guidelines","Brand in Digital Media"],  Array(6).fill("https://www.youtube.com/embed/l-S2Y3SF3jM")),
  10: makeLessons(10, ["Intro to Startups","Idea Validation","Building an MVP","Product Market Fit","Pitching to Investors","Growth Strategies"],                     Array(6).fill("https://www.youtube.com/embed/ZoqgAy3h4OM")),
  11: makeLessons(11, ["Intro to Content Marketing","Keyword Research","Writing SEO Blog Posts","Link Building","Measuring Performance","Content Calendar"],          Array(6).fill("https://www.youtube.com/embed/xsVTqzratPs")),
  12: makeLessons(12, ["Intro to Guitar","First Chords: Em Am D","More Chords: G C E A","Strumming Patterns","Your First Song","Fingerpicking Basics"],               Array(6).fill("https://www.youtube.com/embed/BBz-Jyr23M4")),
  13: makeLessons(13, ["Intro to Node.js","Express.js Fundamentals","Working with MongoDB","JWT Authentication","Deploying to AWS","Security & Rate Limiting"],       Array(6).fill("https://www.youtube.com/embed/Oe421EPjeBE")),
  14: makeLessons(14, ["Intro to After Effects","Keyframes & Animation","Text Animation","Shape Layers","Exporting & Delivery","Advanced Motion Graphics"],           Array(6).fill("https://www.youtube.com/embed/OB4-3VkFCJo")),
  15: makeLessons(15, ["Intro to Financial Modeling","Building a DCF Model","LBO Modeling","Comparable Company Analysis","Presenting Your Model","Sensitivity Analysis"], Array(6).fill("https://www.youtube.com/embed/EJHPltmAULA")),
  16: makeLessons(16, ["Intro to SQL","SELECT WHERE ORDER BY","JOINs","Aggregate Functions & GROUP BY","Database Design & Normalization","Indexes & Performance"],    Array(6).fill("https://www.youtube.com/embed/HXV3zeQKqGY")),
};
